//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long Id { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Comment { get; set; }
        public string UserName { get; set; }
        public string UserIP { get; set; }
        public string UserEmail { get; set; }
    
        public virtual News News { get; set; }
    }
}
