//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticPages
    {
        public long Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string Content { get; set; }
        public long UsersId { get; set; }
        public string Title { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
